### PR TITLE
Add .travis.yml for Travis CI

### PR DESCRIPTION
**Pull request by sodabrew**
Now that there are unit tests, Travis CI provides a free public testing service: http://docs.travis-ci.com/user/getting-started/

### CODE REVIEW

**Comment by thuehlinger** [comment]
Thanks! Travis CI is now set up. However, the 1.8.7 and 1.9.3 tests fail since pry and byebug only install on >= 2.0.0.
Do we need these for rspec?

**Comment by sodabrew** [comment]
I don't think so, pry and byebug are typically used for interactive debugging. We could move these from the .gemspec into the Gemfile, I can submit a PR later today for it.

**Comment by sodabrew** [comment]
I didn't notice, but there's also a circleci set up by @acuppy when he wrote the unit tests: https://circleci.com/gh/acuppy/daemons

Any preference for one service over the other?

**Comment by acuppy** [comment]
Either should work fine. Travis is simple.

**Comment by thuehlinger** [comment]
Good, then Travis it is.

Thomas

**Pull request merged**
