### PR TITLE
Clarify that `run` and `start -t` are equivalent in helptext

### PR DESCRIPTION
**Pull request by rlue**

### CODE REVIEW

**Comment by thuehlinger** [comment]
This seems to fail on Ruby verions < 2.3, see https://travis-ci.org/thuehlinger/daemons/builds/373380037?utm_source=github_status&utm_medium=notification
Can you please try to fix this?

**Comment by rlue** [comment]
Oops, that's because I used the squiggly heredoc (which handles indentation differently than a regular heredoc).

I figured I'd use it since Ruby <2.3 was past end-of-life, but let me switch it back when I get a chance later on this weekend.

**Comment by rlue** [comment]
Whoops, thank heavens for CI!

**Comment by thuehlinger** [comment]
Great, thanks!

**Pull request merged**
